/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/containers/**/*.{js,jsx,ts,tsx}',
    './src/templates/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    scale: {
      '-100': '-1',
    },
    borderRadius: {
      project: '35px',
    },
    extend: {
      keyframes: {
        accordionSlideDown: {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        accordionSlideUp: {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-slide-down': 'accordionSlideDown 300ms ease-out',
        'accordion-slide-up': 'accordionSlideUp 300ms ease-out',
      },
      gridTemplateColumns: {
        16: 'repeat(16, minmax(0, 1fr))',
      },
      fontFamily: {
        roboto: ['Roboto'],
        jost: ['Jost'],
        neo: ['Neo'],
        pretendard: ['Pretendard'],
        'apple-neo': ['Apple SD Gothic Neo'],
      },
      // textColor: {
      //   Text_Color1: ['#8D8A93'],
      //   Text_Color2: ['#525252'],
      //   Text_Color3: ['#CDCDCD'],
      // },
      colors: {
        gradient_color1: ['#F590FA'],
        gradient_color2: ['#81A0F6'],
        mainGra1: ['#f953ff'],
        mainGra2: ['#5a89ff'],
        glass: ['rgba(255, 255, 255, 0.5)'],
        white: ['#FFFFFF'],
        black: ['#111111'],
        gray1: ['#525252'],
        gray2: ['#d4d7db'],
        gray3: ['#ececec'],
        gray4: ['#f9fafb'],
        purple: ['#db95fa'],
        blue: ['#5a47cc'],
        bluegray1: ['#98a4cd'],
        bluegray2: ['#d8def2'],
        bluegray3: ['#e9ecf6'],
        bluegray4: ['#f4f6fc'],
        bg: {
          basicDefault: "#ffffff",
          basicLight: "#F7F8F8",
          basicStrong: "#F1F1F4",
          basicBlack: "#25262C",
          brandPrimary: "#6B5CFF",
          brandSecondary: "#ECEFFF",
          statusNegative: "#FF5C5C",
          statusPositive: "#6B5CFF",
        },
        text: {
          basicPrimary: "#25262C",
          basicSecondary: "#4B505D",
          basicTertiary: "#6E7687",
          basicDisabled: "#B5B9C4",
          basicWhite: "#ffffff",
          brandPrimary: "#6B5CFF",
          brandSecondary: "#ECEFFF",
          statusNegative: "#FF5C5C",
          statusPositive: "#6B5CFF",
        },
        line: {
          basicLight: "#F1F1F4",
          basicMedium: "#E3E4E8",
          basicStrong: "#B5B9C4",
          brandPrimary: "#6B5CFF",
          statusNegative: "#FF5C5C",
          statusPositive: "#6B5CFF",
        },
        button: {
          filledPrimaryEnabled: "#6B5CFF",
          filledPrimaryPressed: "#4B2AD8",
          filledPrimaryDisabled: "#F1F1F4",
          filledSecondaryEnabled: "#ECEFFF",
          filledSecondaryPressed: "#C2C8FF",
          filledSecondaryDisabled: "#F1F1F4",
          outlinedEnabled: "#FFFFFF00",
          outlinedPressed: "#F1F1F4",
          outlinedDisabled: "#FFFFFF00",
          textPrimaryEnabled: "#FFFFFF00",
          textPrimaryPressed: "#ECEFFF",
          textPrimaryDisabled: "#FFFFFF00",
          textSecondaryEnabled: "#FFFFFF00",
          textSecondaryPressed: "#F1F1F4",
          textSecondaryDisabled: "#FFFFFF00",
          fabPrimaryEnabled: "#6B5CFF",
          fabPrimaryPressed: "#4B2AD8",
          fabPrimaryDisabled: "#F1F1F4",
          fabSecondaryEnabled: "#FFFFFF",
          fabSecondaryPressed: "#F1F1F4",
          fabSecondaryDisabled: "#ffffff",
          radioSelected: "#6B5CFF",
          radioUnselected: "#E3E4E8",
          radioDisabled: "#ffffff",
        },
        icon: {
          basicPrimary: "#25262C",
          basicSecondary: "#4B505D",
          basicTertiary: "#6E7687",
          basicDisabled: "#E3E4E8",
          basicDisabledStrong: "#B5B9C4",
          basicWhite: "#ffffff",
          brandPrimary: "#6B5CFF",
          brandSecondary: "#5736F5",
        },
        checkboxSelected: "#6B5CFF",
        checkboxUnselected: "#FFFFFF",
        checkboxDisabled: "#E3E4E8",
        chipSelected: "#DDE1FF",
        chipUnselected: "#F1F1F4",
        chipDisabled: "#F7F8F8",
        pagination: {
          brandPressed: "#ECEFFF",
          basicSelected: "#25262C",
          basicUnselected: "#E3E4E8",
        },
        switch: {
          selected: "#6B5CFF",
          unselected: "#B5B9C4",
          disabled: "#E3E4E8",
          thumb: "#FFFFFF",
        },
        snackbar: {
          info: "#3F434D",
          error: "#FFEBEB",
        },
      },
    },
    screens: {
      xs: { min: '0px', max: '350px' },
      sm: { min: '350px', max: '720px' },
      md: { min: '721px', max: '1080px' },
      lg: { min: '1081px', max: '1440px' },
      xl: { min: '1441px', max: '1920px' },
      xxl: { min: '1921px' },
    },
  },
  plugins: [],
};
