name: build-and-deploy

on:
  push:
    branches: [master]
  repository_dispatch:
    types: [sanity-content-update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Clean Gatsby build
        run: ./node_modules/.bin/gatsby clean

      - name: Generate Environment Variables File for Production
        run: |
          echo "GATSBY_APP_SANITY_TOKEN=$GATSBY_APP_SANITY_TOKEN" >> .env
          echo "GATSBY_APP_SANITY_PROJECT_ID=$GATSBY_APP_SANITY_PROJECT_ID" >> .env
          echo "GATSBY_APP_SANITY_DATASET=$GATSBY_APP_SANITY_DATASET" >> .env
          echo "GATSBY_APP_GA_ID=$GATSBY_APP_GA_ID" >> .env
        env:
          GATSBY_APP_SANITY_TOKEN: ${{ secrets.GATSBY_APP_SANITY_TOKEN }}
          GATSBY_APP_SANITY_PROJECT_ID: ${{ secrets.GATSBY_APP_SANITY_PROJECT_ID }}
          GATSBY_APP_SANITY_DATASET: ${{ secrets.GATSBY_APP_SANITY_DATASET }}
          GATSBY_APP_GA_ID: ${{ secrets.GATSBY_APP_GA_ID }}

      - name: build application
        run: ./node_modules/.bin/gatsby build

      - name: Deploy to S3 using gatsby-plugin-s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
        run: ./node_modules/.bin/gatsby-plugin-s3 deploy --yes
